import logging
import time

import altair
import geopandas
import jinja2
import numpy
import os

from natcap.invest import utils, validation
from natcap.invest import __version__
from natcap.invest import gettext
from natcap.invest.reports import raster_utils, report_constants, \
    vector_utils
from natcap.invest.spec import ModelSpec

from natcap.invest.reports.raster_utils import RasterDatatype, \
    RasterPlotConfig


LOGGER = logging.getLogger(__name__)

jinja_env = jinja2.Environment(
    loader=jinja2.ChoiceLoader([
        jinja2.PackageLoader('invest_plugin_for_workshop', 'template'),
        jinja2.PackageLoader('natcap.invest.reports', 'templates'),
    ]),
    autoescape=jinja2.select_autoescape(),
    undefined=jinja2.StrictUndefined
)

TEMPLATE = jinja_env.get_template('birb_report_template.html')

MAP_WIDTH = 450  # pixels


def report(file_registry: dict, args_dict: dict, model_spec: ModelSpec,
           target_html_filepath: str):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """

    output_raster_config_list = [
        RasterPlotConfig(
            raster_path=file_registry['birb_count_raster'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_output('birb_count_raster')
        )
    ]

    if args_dict.get('birb_population_density_table'):
        birb_list = utils.read_csv_to_dataframe(
            args_dict['birb_population_density_table'])['group']
        birb_group_config_list = []
        for group in birb_list:
            if str(group) in file_registry[
                    '[GROUP]_count_raster']:
                birb_group_config_list.append(
                    RasterPlotConfig(
                        raster_path=file_registry[
                            '[GROUP]_count_raster'][
                                str(group)],
                        datatype=RasterDatatype.continuous,
                        spec=model_spec.get_output(
                            '[GROUP]_count_raster'),
                    )
                )
        birb_group_img_src = raster_utils.plot_and_base64_encode_rasters(
            birb_group_config_list)
        birb_group_caption = raster_utils.caption_raster_list(
            birb_group_config_list)
    else:
        birb_group_img_src = None
        birb_group_caption = None

    lulc_img_src, lulc_legend_html = raster_utils.plot_categorical_raster_with_table(
        [args_dict['lulc_raster']])
    lulc_caption = f"{os.path.basename(args_dict['lulc_raster'])}:" \
        f"{model_spec.get_input('lulc_raster').about}"

    outputs_img_src = raster_utils.plot_and_base64_encode_rasters(
        output_raster_config_list)
    outputs_raster_caption = raster_utils.caption_raster_list(
        output_raster_config_list)

    input_raster_stats_table = raster_utils.raster_inputs_summary(
        args_dict, model_spec).to_html(na_rep='')

    output_raster_stats_table = raster_utils.raster_workspace_summary(
        file_registry).to_html(na_rep='')

    if args_dict.get("aoi_path"):
        agg_results_gdf = geopandas.read_file(file_registry['aggregated_results_vector'])
        _, xy_ratio = vector_utils.get_geojson_bbox(agg_results_gdf)

        agg_results_json = vector_utils.create_aggregate_map(
            agg_results_gdf, xy_ratio, 'number_of_birbs',
            'viridis', "Number of Birbs")
        agg_results_map_source_list = [
            model_spec.get_output('aggregated_results_vector').path
        ]
        vector_plot_caption = [
            model_spec.get_output('aggregated_results_vector')
            .get_field('number_of_birbs').about
        ]
    else:
        agg_results_json = None
        agg_results_map_source_list = None
        vector_plot_caption = None


    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            report_script=model_spec.reporter,
            invest_version=__version__,
            report_filepath=target_html_filepath,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            model_description=model_spec.about,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            birb_group_img_src=birb_group_img_src,
            birb_group_caption=birb_group_caption,
            lulc_img_src=lulc_img_src,
            lulc_legend_html=lulc_legend_html,
            lulc_caption=lulc_caption,
            outputs_img_src=outputs_img_src,
            outputs_caption=outputs_raster_caption,
            raster_group_caption=report_constants.RASTER_GROUP_CAPTION,
            output_raster_stats_table=output_raster_stats_table,
            input_raster_stats_table=input_raster_stats_table,
            stats_table_note=report_constants.STATS_TABLE_NOTE,
            agg_results_json=agg_results_json,
            vector_plot_caption=vector_plot_caption,
            agg_results_map_source_list=agg_results_map_source_list,
            model_spec_outputs=model_spec.outputs,
        ))

    LOGGER.info(f'Created {target_html_filepath}')
